export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const AGREGAR_HEROE = 'AGREGAR_HEROE';
export const ELIMINAR_HEROE = 'ELIMINAR_HEROE';
export const CAMBIAR_PANTALLA = 'CAMBIAR_PANTALLA';
export const CAMBIAR_PANTALLA_BUSCAR = 'CAMBIAR_PANTALLA_BUSCAR';
export const LIMPIAR_HEROES = 'LIMPIAR_HEROES';
